server:
    #address: localhost
    port: 8083
    
    
spring:
    application:
        name: CSquare-UMS
   
        
    http: 
      multipart: 
        max-file-size: 10MB
        max-request-size: 10MB

    datasource:
        url: jdbc:postgresql://localhost:5432/csquare
        driverClassName: org.postgresql.Driver
        username: postgres
        password: password
    jpa:
       hibernate:
         ddl-auto: create
         c3p0: 
            min_size: 5
            max_size: 100
            timeout: 120
            max_statements: 100
         naming: 
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
       properties: 
             hibernate:
               dialect: org.hibernate.dialect.PostgreSQLDialect
       show-sql: true    
       
  
      